apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: unikorn-identity
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
- apiGroups:
  - unikorn-cloud.org
  resources:
  - oauth2clients
  - oauth2mappings
  - oauth2providers
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
