apiVersion: v2
name: unikorn
description: A Helm chart for deploying Unikorn

type: application

version: v0.4.0
appVersion: v0.4.0

icon: https://raw.githubusercontent.com/spjmurray/unikorn/main/icons/default.png
