apiVersion: v2
name: unikorn
description: A Helm chart for deploying Unikorn

type: application

version: v0.3.61
appVersion: v0.3.61

icon: https://raw.githubusercontent.com/eschercloudai/unikorn/main/icons/default.png
